### ISSUE TITLE
Error with image-to-ascii

### ISSUE THREAD

**Issue by enjikaka** [IonicaBizau/ansy#1]
When using the example

```
// Dependencies
const imageToAscii = require("image-to-ascii");

// The path can be either a local path or an url
imageToAscii("https://octodex.github.com/images/octofez.png", (err, converted) => {
    console.log(err || converted);
});

// Passing options
imageToAscii("https://octodex.github.com/images/privateinvestocat.jpg", {
    colored: false
}, (err, converted) => {
    console.log(err || converted);
});
```

this shows up:

```
/ascii/node_modules/ansy/lib/index.js:27
  , { fg: ansiStyles.color.ansi, bg: ansiStyles.bgColor.ansi }
                          ^

TypeError: Cannot read property 'ansi' of undefined
    at Object.<anonymous> (/Users/jeremy/Dev/ascii/node_modules/ansy/lib/index.js:27:27)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jeremy/Dev/ascii/node_modules/couleurs/lib/index.js:6:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

```

**Comment by IonicaBizau** [comment]
@enjikaka Hmm, interesting. Can you provide some info about the terminal emulator you're using? It looks like the color support is not detected.

You can force it by running`node your-script.js --color=256`.

**Comment by enjikaka** [comment]
I'm using iTerm 2.9.20160313.

**Comment by enjikaka** [comment]
I get the same error when running it with `--color=256`

**Comment by IonicaBizau** [comment]
@enjikaka Can you please run the example from [this package](https://github.com/chalk/ansi-styles)?

**Comment by enjikaka** [comment]
```
Hello world!
/Users/jeremy/Dev/ascii/ansi.js:10
console.log(style.bgColor.ansi.hsl(120, 80, 72) + 'Hello world!' + style.bgColor.close);
                         ^

TypeError: Cannot read property 'ansi' of undefined
    at Object.<anonymous> (/Users/jeremy/Dev/ascii/ansi.js:10:26)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

![](http://i.imgur.com/WQ1Dt5I.png)

**Comment by IonicaBizau** [comment]
@enjikaka Hmm, then that's the problem. Can you please [open an issue there](https://github.com/chalk/ansi-styles/issues/new) and ping me when it's fixed?

**Comment by Qix-** [comment]
You'll need to temporarily change your dependency from `^2.2.0` to `chalk/ansi-styles` in package.json. You guys are using the shiny new API for ansi-styles that should have been released as 3.0.0 but instead was released as a minor bump (2.2.0).

There's more info in @enjikaka's issue over at chalk/ansi-styles#18 as well as [this post-mortem](https://github.com/chalk/ansi-styles/issues/15#issuecomment-202589714). Sorry for the inconvenience; we've been battling a bad release for a few days now.

---

On a personal note, a lot of effort was put into the new API, both in ansi-styles and upstream, and it makes me happy to see someone using it :heart:.

**Comment by Qix-** [comment]
@IonicaBizau Hopefully that fixes things. Again, extremely sorry about this. I'll open a PR here when we do a release. :+1:

**Comment by IonicaBizau** [comment]
I just published a patch upgrade: 1.0.1. :ship: 

@Qix- Thanks for the solution!

@enjikaka Reinstall the dependencies of `image-to-ascii` (or specifically `ansy`). Would like to hear it's working. :grin:

**Comment by IonicaBizau** [comment]
@Qix- No worries, not sure why it only happens on specific terminals. I'm using Linux on three machines (desktop, laptop and raspberry pi) and it's working perfectly. :joy:

**Comment by Qix-** [comment]
``` console
$ nvm use 5
$ npm i ansy
```

<img width="459" alt="screen shot 2016-03-31 at 9 57 41 am" src="https://cloud.githubusercontent.com/assets/885648/14183840/196c3a26-f727-11e5-9b2c-55e9cc759c72.png">

---

> not sure why it only happens on specific terminals

Believe me, this whole process has been weird. Someone else experienced the correct version of chalk but a super old version of ansi-styles being downloaded by npm - even after clearing everything out and re-installing.

**Comment by IonicaBizau** [comment]
@enjikaka Looks good. :dizzy: Hmm... bugs are everywhere.

**Comment by enjikaka** [comment]
Cool! Gonna try at work tomorrow! :computer:

**Comment by IonicaBizau** [comment]
Going to close this. Hopefully it works. Just ping me for any questions/bug reports/features etc. :bell:
